name: search_package
description: A Dart package that provides efficient implementations of various search algorithms, including Linear Search, Binary Search, and Jump Search. Ideal for both numerical and string data, this package includes performance metrics to help developers assess search efficiency in their applications.
version: 1.0.1
repository: https://github.com/asadbekxomidov/search_package

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
